DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

DROP TABLE IF EXISTS DIA CASCADE;
DROP TABLE IF EXISTS HORA CASCADE;
DROP TABLE IF EXISTS PISO CASCADE;
DROP TABLE IF EXISTS CONSULTORIO CASCADE;
DROP TABLE IF EXISTS CARGO CASCADE;
DROP TABLE IF EXISTS ESPECIALIDAD CASCADE;
DROP TABLE IF EXISTS TELEFONO CASCADE;
DROP TABLE IF EXISTS CORREO CASCADE;
DROP TABLE IF EXISTS MEDICO_CONSULTORIO CASCADE;
DROP TABLE IF EXISTS DIA_CONSULTORIO CASCADE;
DROP TABLE IF EXISTS DIA_HORA CASCADE;
DROP TABLE IF EXISTS DIA_ESPECIALIDAD CASCADE;
DROP TABLE IF EXISTS PERTENENCIA CASCADE;
DROP TABLE IF EXISTS ASISTENCIA CASCADE;
DROP TABLE IF EXISTS MEDICO CASCADE;